version: '3'
services:
  complaintservice:
    image: complaint-service
    ports:
      - 8080:8080
    networks:
      - desenv-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - desenv-network

networks:
  desenv-network:
    driver: "bridge"